// Test-only environment. Production code reads configuration exclusively through src/config/env.ts;
// this file just provides valid values before that module is first imported.
Object.assign(process.env, {
  NODE_ENV: 'test',
  SERVER_PORT: '3999',
  API_BASE_URL: 'https://api.test.example',
  WEB_APP_URL: 'https://app.test.example',
  REQUEST_BODY_LIMIT: '100kb',
  CORS_ALLOWED_ORIGINS: 'https://app.test.example,https://admin.test.example',
  TRUST_PROXY_HOPS: '0',
  MONGODB_URI: 'mongodb://127.0.0.1:27017/unused-in-tests',
  MONGODB_QUERY_MAX_LIMIT: '100',
  ANALYTICS_MAX_ITEMS: '5000',
  JWT_SECRET: 'test-secret-test-secret-test-secret-123456',
  JWT_ACCESS_EXPIRES_IN: '15m',
  JWT_REFRESH_EXPIRES_IN: '30d',
  PASSWORD_HASH_ROUNDS: '10',
  LOGIN_MAX_FAILED_ATTEMPTS: '3',
  LOGIN_LOCKOUT_MINUTES: '15',
  PASSWORD_RESET_TOKEN_TTL_MINUTES: '30',
  MAX_SESSIONS_PER_USER: '5',
  CREDENTIAL_ENCRYPTION_KEY: Buffer.alloc(32, 7).toString('base64'),
  RATE_LIMIT_WINDOW_MS: '60000',
  RATE_LIMIT_GENERAL_MAX: '10000',
  RATE_LIMIT_AUTH_MAX: '10000',
  RATE_LIMIT_SYNC_MAX: '10000',
  RATE_LIMIT_AI_MAX: '10000',
  RATE_LIMIT_UPLOAD_MAX: '10000',
  RATE_LIMIT_ADMIN_MAX: '10000',
  PROVIDER_TIMEOUT_MS: '2000',
  PROVIDER_MAX_RETRIES: '2',
  PROVIDER_RETRY_BASE_MS: '1',
  PROVIDER_MAX_PAGES: '10',
  META_API_VERSION: 'v21.0',
  YOUTUBE_API_VERSION: 'v3',
  LINKEDIN_API_VERSION: '202401',
  OAUTH_STATE_TTL_SECONDS: '600',
  SYNC_INTERVAL_MINUTES: '60',
  SYNC_TIMEOUT_MS: '5000',
  SYNC_LEASE_SECONDS: '30',
  SYNC_MAX_ATTEMPTS: '3',
  SYNC_WORKER_ENABLED: 'false',
  SYNC_WORKER_POLL_MS: '100',
  SYNC_SCHEDULER_ENABLED: 'false',
  JOBS_TRIGGER_SECRET: 'jobs-secret-for-tests',
  AI_TIMEOUT_MS: '3000',
  AI_MAX_INPUT_CHARS: '20000',
  AI_CACHE_TTL_HOURS: '24',
  GEMINI_API_KEY: 'test-key',
  GEMINI_MODEL: 'test-model',
  FILE_MAX_BYTES: '1048576',
  FILE_ALLOWED_MIME_TYPES: 'image/png,image/jpeg,application/pdf',
  FILE_PRESIGNED_URL_TTL_SECONDS: '300',
  R2_ACCOUNT_ID: 'acct', R2_ACCESS_KEY_ID: 'key', R2_SECRET_ACCESS_KEY: 'secret', R2_BUCKET: 'bucket', R2_ENDPOINT: 'https://r2.test.example',
  META_APP_ID: 'meta-app', META_APP_SECRET: 'meta-secret', META_REDIRECT_URI: 'https://api.test.example/api/v1/connections/oauth/instagram/callback',
  YOUTUBE_CLIENT_ID: 'yt-id', YOUTUBE_CLIENT_SECRET: 'yt-secret', YOUTUBE_REDIRECT_URI: 'https://api.test.example/api/v1/connections/oauth/youtube/callback',
  LINKEDIN_CLIENT_ID: 'li-id', LINKEDIN_CLIENT_SECRET: 'li-secret', LINKEDIN_REDIRECT_URI: 'https://api.test.example/api/v1/connections/oauth/linkedin/callback',
});
// SMTP is intentionally NOT configured so the "email not configured" path is exercised.
delete process.env.SMTP_HOST;
